cron = "3,7 6,12,18 * * *"

BaseURL = "https://xxcapp.xidian.edu.cn"
LoginURL = "https://xxcapp.xidian.edu.cn/uc/wap/login/check"
SaveURL = "https://xxcapp.xidian.edu.cn/xisuncov/wap/open-report/save"
MyUserAgent = "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.45 Mobile Safari/537.36 Edg/84.0.522.20"